version: "3.9"

services:
  tg2qqpd:
    build: ./backend
    restart: always
    env_file: .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data/sqlite:/app/data
      - ./data/tg_session:/app/sessions
      - ./data/tg_media:/tmp
      - ./config.yaml:/app/config.yaml:ro
    ports:
      - "8000:8000"
